"""Tables

Revision ID: 980742dba9e4
Revises: 44d76478702b
Create Date: 2025-07-24 18:34:31.283787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '980742dba9e4'
down_revision: Union[str, Sequence[str], None] = '44d76478702b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'occupation',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'occupation_grade',
               existing_type=postgresql.ENUM('TRAINEE', 'JUNIOR', 'MIDDLE', 'SENIOR', 'LEAD', name='occupationgrades'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'occupation_grade',
               existing_type=postgresql.ENUM('TRAINEE', 'JUNIOR', 'MIDDLE', 'SENIOR', 'LEAD', name='occupationgrades'),
               nullable=False)
    op.alter_column('users', 'occupation',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
